import { LOGO, type LogoPath } from "@/lib/logo";

/* The live Girling Jones logo, drawn from its own vector paths (lib/logo.ts, generated by scripts/logo.mjs).
   Colours come from CSS: the monogram, rules and tagline use --logo-ink (white on dark ground, ink on light),
   the twelve wordmark letters use --lime. With `parts` every piece is tagged so the preloader can animate it. */
// The offset sits on a wrapping <g> so the preloader can move and scale the <path> itself without overwriting it.
const P = ({ p, part, index }: { p: LogoPath; part: string; index?: number }) =>
  <g transform={`translate(${p.x} ${p.y})`}><path d={p.d} data-part={part || undefined} data-index={index} /></g>;

export function Logo({ title = "Girling Jones", className = "", parts = false, markOnly = false }: { title?: string; className?: string; parts?: boolean; markOnly?: boolean }) {
  const viewBox = markOnly ? "0 0 40 71.504" : LOGO.viewBox;
  return <svg className={`logo ${className}`} viewBox={viewBox} role={title ? "img" : undefined} aria-label={title || undefined} aria-hidden={title ? undefined : true} focusable="false">
    <g className="logo-mark"><P p={LOGO.mark} part={parts ? "mark" : ""} /></g>
    {!markOnly && <>
      <g className="logo-rules">{LOGO.rules.map((r, i) => <P key={i} p={r} part={parts ? "rule" : ""} index={i} />)}</g>
      <g className="logo-tagline"><P p={LOGO.tagline} part={parts ? "tagline" : ""} /></g>
      <g className="logo-letters">{LOGO.letters.map((l, i) => <P key={i} p={l} part={parts ? "letter" : ""} index={i} />)}</g>
    </>}
  </svg>;
}
