// Splits the live vector logo (girlingjones.com/wp-content/uploads/2021/11/Logo.svg) into named parts for
// the preloader and header, and writes lib/logo.ts plus light/dark SVG files in public/brand.
// Usage: npm run logo
//
// Every transform in the source file is a plain translate(), nested up to three groups deep, so each path's
// groups are summed into one offset. Parts:
//   mark    – the white "gj" monogram (one merged outline: the g and j share a contour, so it is drawn as one stroke)
//   letters – g·i·r·l·i·n·g·j·o·n·e·s, twelve separate paths, left to right
//   rules   – the two hairlines either side of the descender of the "g" and "j"
//   tagline – "THE RECRUITMENT CONSULTANTS" as one compound path
import { mkdir, readFile, writeFile } from "node:fs/promises";

const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36";
const res = await fetch("https://girlingjones.com/wp-content/uploads/2021/11/Logo.svg", { headers: { "user-agent": UA } });
const svg = res.ok ? await res.text() : await readFile(new URL("../_scrape/logo.svg", import.meta.url), "utf8");

const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
const translate = (attrs) => {
  const m = /transform="translate\(([-\d.]+)[ ,]+([-\d.]+)\)"/.exec(attrs ?? "");
  return m ? [parseFloat(m[1]), parseFloat(m[2])] : [0, 0];
};

// Walk the tags in order, keeping a stack of group offsets.
const stack = [[0, 0]];
const paths = {};
for (const tag of svg.matchAll(/<(\/?)(g|path)\b([^>]*?)(\/?)>/g)) {
  const [, close, name, attrs, selfClose] = tag;
  if (name === "g" && close) { stack.pop(); continue; }
  const [tx, ty] = translate(attrs);
  const [px, py] = stack[stack.length - 1];
  if (name === "g") { stack.push([px + tx, py + ty]); continue; }
  const id = /id="([^"]+)"/.exec(attrs)[1];
  const d = /\sd="([^"]+)"/.exec(attrs)[1];
  const fill = /fill="([^"]+)"/.exec(attrs)?.[1];
  paths[id] = { d, x: +(px + tx).toFixed(3), y: +(py + ty).toFixed(3), fill };
  if (selfClose) continue;
}

const part = (id) => ({ d: paths[id].d, x: paths[id].x, y: paths[id].y });
const logo = {
  viewBox,
  mark: part("Path_208"),
  letters: Array.from({ length: 12 }, (_, i) => part(`Path_${209 + i}`)),
  rules: [part("Path_205"), part("Path_206")],
  tagline: part("Path_207"),
  // Original fills: the mark, rules and tagline are white (the logo is built for dark grounds); the letters are #80ba27.
  sourceFills: { mark: paths.Path_208.fill, letters: paths.Path_209.fill },
};

const ts = `// Generated by scripts/logo.mjs from the live Logo.svg. Do not edit by hand.
// Each part carries its summed translate() offset; see components/Logo.tsx for how the parts are drawn.
export type LogoPath = { d: string; x: number; y: number };

export const LOGO = ${JSON.stringify(logo, null, 2)} as const;
`;
await writeFile(new URL("../lib/logo.ts", import.meta.url), ts);

// Static files: one for dark grounds (white mark), one for light grounds (ink mark). Letters use the site green.
const file = (ink) => {
  const p = (x, fill) => `<path d="${x.d}" transform="translate(${x.x} ${x.y})" fill="${fill}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${p(logo.mark, ink)}${logo.rules.map((r) => p(r, ink)).join("")}${p(logo.tagline, ink)}${logo.letters.map((l) => p(l, "#98d639")).join("")}</svg>\n`;
};
await mkdir(new URL("../public/brand/", import.meta.url), { recursive: true });
await writeFile(new URL("../public/brand/logo-on-dark.svg", import.meta.url), file("#ffffff"));
await writeFile(new URL("../public/brand/logo-on-light.svg", import.meta.url), file("#221f20"));
const [, , w, h] = viewBox.split(" ").map(Number);
await writeFile(new URL("../public/brand/mark.svg", import.meta.url), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${75} ${h}"><path d="${logo.mark.d}" transform="translate(${logo.mark.x} ${logo.mark.y})" fill="#221f20"/></svg>\n`);
console.log(`logo: ${Object.keys(paths).length} paths, viewBox ${w}×${h}`);
